controller_list:
  - name: fake_arm_motion_group_controller
    type: $(arg fake_execution_type)
    joints:
      # - robot_arm_mount_to_actuator
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
  - name: fake_scrubbing_tool_controller
    type: $(arg fake_execution_type)
    joints:
      - joint6output_to_joint6
initial:  # Define initial robot poses per group
  - group: arm_motion_group
    pose: init_pose
  - group: scrubbing_tool
    pose: scrubbing_init_pose