# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_motion_group
  joint_model_group_pose: init_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    # - robot_arm_mount_to_actuator
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# # Publish all joint states
# # Creates the /joint_states topic necessary in ROS
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

# robot_arm_mount_to_actuator_controller:
#   type: effort_controllers/JointPositionController
#   joint: robot_arm_mount_to_actuator
#   pid: {p: 35000, i: 1.0, d: 100.0}

joint2_to_joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2_to_joint1
  pid: {p: 350, i: 1.0, d: 150.0}

joint3_to_joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint3_to_joint2
  pid: {p: 350, i: 1.0, d: 150.0}

joint4_to_joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint4_to_joint3
  pid: {p: 350, i: 1.0, d: 50.0}

joint5_to_joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint5_to_joint4
  pid: {p: 350, i: 1.0, d: 50.0}

joint6_to_joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint6_to_joint5
  pid: {p: 350, i: 1.0, d: 50.0}

joint6output_to_joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint6output_to_joint6
  pid: {p: 350, i: 1.0, d: 50.0}


# arm_motion_group_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - robot_arm_mount_to_actuator
#     - joint2_to_joint1
#     - joint3_to_joint2
#     - joint4_to_joint3
#     - joint5_to_joint4
#     - joint6_to_joint5
#     - joint6output_to_joint6
#   gains:
#     robot_arm_mount_to_actuator: { p: 100, d: 50, i: 1, i_clamp: 1}
#     joint2_to_joint1: { p: 100, d: 50, i: 1, i_clamp: 1 }
#     joint3_to_joint2: { p: 100, d: 50, i: 1, i_clamp: 1 }
#     joint4_to_joint3: { p: 100, d: 50, i: 1, i_clamp: 1 }
#     joint5_to_joint4: { p: 100, d: 50, i: 1, i_clamp: 1 }
#     joint6_to_joint5: { p: 100, d: 50, i: 1, i_clamp: 1 }
#     joint6output_to_joint6: { p: 100, d: 50, i: 1, i_clamp: 1 }
#   constraints:
#     goal_time: 2.0
#   state_publish_rate: 25