# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: init_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_motion_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6

arm_motion_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6
  gains:
        joint2_to_joint1: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
        joint3_to_joint2: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
        joint4_to_joint3: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
        joint5_to_joint4: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
        joint6_to_joint5: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
        joint6output_to_joint6: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }
  constraints:
      goal_time: 2.0
  state_publish_rate: 25