controller_manager_ns: controller_manager
controller_list:
  - name: arm_motion_group_controller
    # action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - robot_arm_mount_to_actuator
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6